const firebaseConfig={apiKey:'AIzaSyAFCAqMsz8RkfS4JpAIVUT27CrWr2cCtJs',authDomain:'chat-fe97c.firebaseapp.com',databaseURL:'https://chat-fe97c-default-rtdb.firebaseio.com',projectId:'chat-fe97c',storageBucket:'chat-fe97c.firebasestorage.app',messagingSenderId:'577320453917',appId:'1:577320453917:web:fbea459344dc71d1ad03f4',measurementId:'G-86YZ76HRJ3'};
let auth=null,db=null;
const $=s=>document.querySelector(s);
const ADMIN_CONFIGURED=typeof ADMIN_EMAIL==='string'&&!ADMIN_EMAIL.startsWith('CHANGE_THIS');
const safe=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const dateValue=v=>v?.toDate?v.toDate():v?.seconds?new Date(v.seconds*1000):null;
const fmt=v=>{const d=dateValue(v);return d?d.toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—'};
const img=n=>n?.imageData||n?.imageUrl||'';
function msg(t,good=false){const e=$('#message');if(!e)return;e.textContent=t;e.className='message '+(good?'good':'bad')}
function setBusy(b){const btn=$('#loginForm button[type=submit]');if(btn){btn.disabled=b;btn.textContent=b?'Signing in…':'Login to Admin Panel'}const email=$('#email'),pass=$('#password');if(email)email.disabled=b;if(pass)pass.disabled=b}
function loadScript(src){return new Promise((ok,no)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=()=>no(new Error('Failed to load Firebase component: '+src));document.head.appendChild(s)})}
function openDashboard(user){if(!user||!user.email){console.error('[ManaMahabubabad Admin] No Firebase user to open dashboard');return false}const email=user.email.toLowerCase(),admin=String(ADMIN_EMAIL||'').toLowerCase();console.log('[ManaMahabubabad Admin] Opening dashboard for',email);if(email!==admin){msg('This Firebase account is not authorized as the site administrator.');return false}const loginView=document.getElementById('loginView'),dash=document.getElementById('dashboardView'),emailBox=document.getElementById('adminEmail');if(!loginView||!dash){throw new Error('Admin page UI is incomplete: loginView/dashboardView not found.')}loginView.hidden=true;loginView.style.display='none';dash.hidden=false;dash.style.display='block';if(emailBox)emailBox.textContent=user.email;setBusy(false);msg('Login successful.',true);console.log('[ManaMahububabad Admin] Dashboard opened');setTimeout(()=>loadAll().catch(e=>{console.error('[ManaMahabubabad Admin] Firestore load failed',e);const list=document.getElementById('newsList');if(list)list.innerHTML='<div class="empty">Dashboard is open, but news could not be loaded.<br>'+safe(e.message||'Firestore error')+'</div>'}),0);return true}
function timeout(ms){return new Promise((_,reject)=>setTimeout(()=>reject(Object.assign(new Error('Firebase sign-in timed out after '+Math.round(ms/1000)+' seconds.'),{code:'auth/timeout'})),ms))}
async function boot(){try{if(!ADMIN_CONFIGURED){msg('Admin email is not configured.');return}msg('Loading Firebase…',true);await loadScript('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js');await loadScript('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth-compat.js');await loadScript('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore-compat.js');if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);auth=firebase.auth();db=firebase.firestore();console.log('[ManaMahabubabad Admin] Firebase initialized',firebaseConfig.projectId,location.origin);const form=$('#loginForm');if(form)form.addEventListener('submit',login);auth.onAuthStateChanged(u=>{console.log('[ManaMahabubabad Admin] Auth state:',u?.email||'signed out');if(u)openDashboard(u);else{if($('#dashboardView'))$('#dashboardView').hidden=true;if($('#dashboardView'))$('#dashboardView').style.display='none';if($('#loginView')){$('#loginView').hidden=false;$('#loginView').style.display='grid'}}});if(auth.currentUser)openDashboard(auth.currentUser);else msg('',true)}catch(e){console.error('[ManaMahabubabad Admin] boot error',e);msg('Firebase initialization failed: '+(e.message||e.code||'Unknown error'))}}
async function login(e){e.preventDefault();console.log('[ManaMahabubabad Admin] Login started');setBusy(true);try{if(!auth)throw new Error('Firebase is still loading.');const email=$('#email').value.trim(),pass=$('#password').value;if(!email||!pass){msg('Enter both admin email and password.');setBusy(false);return}if(email.toLowerCase()!==String(ADMIN_EMAIL).toLowerCase()){msg('Wrong admin account.');setBusy(false);return}console.log('[ManaMahabubabad Admin] Calling Firebase signInWithEmailAndPassword');const result=await Promise.race([auth.signInWithEmailAndPassword(email,pass),timeout(15000)]);console.log('[ManaMahabubabad Admin] Sign-in resolved',result?.user?.email||'no user');const user=result?.user||auth.currentUser;if(!user)throw new Error('Firebase returned no user session.');openDashboard(user)}catch(err){console.error('[ManaMahabubabad Admin] Login error',err);const map={'auth/user-not-found':'This email is not registered in Firebase Authentication.','auth/wrong-password':'The password is incorrect.','auth/invalid-credential':'Invalid admin email or password.','auth/invalid-email':'The email address is invalid.','auth/operation-not-allowed':'Email/Password sign-in is disabled in Firebase Authentication.','auth/too-many-requests':'Too many login attempts. Try again later.','auth/network-request-failed':'Network error while contacting Firebase.','auth/internal-error':'Firebase returned an internal authentication error.','auth/timeout':'Firebase sign-in timed out after 15 seconds.'};msg(map[err.code]||((err.code?err.code+': ':'')+(err.message||'Admin login failed.')));setBusy(false)}}
async function loadAll(){if(!db||!auth?.currentUser)return;const snap=await db.collection('news').get();const rows=[];snap.forEach(d=>rows.push({id:d.id,...d.data()}));rows.sort((a,b)=>(dateValue(b.createdAt)?.getTime()||0)-(dateValue(a.createdAt)?.getTime()||0));renderStats(rows);renderList(rows)}
function renderStats(rows){$('#total').textContent=rows.length;$('#pending').textContent=rows.filter(n=>n.status==='UnderReview'&&!n.rejected&&!n.published).length;$('#published').textContent=rows.filter(n=>n.published||n.status==='Published').length;$('#rejected').textContent=rows.filter(n=>n.rejected||n.status==='Rejected').length}
function renderList(rows){const filter=$('#filter').value;const show=rows.filter(n=>{if(filter==='pending')return n.status==='UnderReview'&&!n.rejected&&!n.published;if(filter==='published')return n.published||n.status==='Published';if(filter==='rejected')return n.rejected||n.status==='Rejected';return true});const list=$('#newsList');if(!show.length){list.innerHTML='<div class="empty">No stories in this section.</div>';return}list.innerHTML=show.map(n=>{const pending=n.status==='UnderReview'&&!n.rejected&&!n.published;const published=n.published||n.status==='Published';const rejected=n.rejected||n.status==='Rejected';let actions='';if(pending)actions=`<button class="approve" data-action="approve" data-id="${n.id}">✓ Approve</button><button class="reject" data-action="reject" data-id="${n.id}">✕ Reject</button>`;if(!pending)actions+=`<button class="delete" data-action="delete" data-id="${n.id}">Delete</button>`;return `<article class="news-item"><div class="thumb">${img(n)?`<img src="${safe(img(n))}" alt="">`:'NEWS'}</div><div class="story"><div class="top"><span class="tag">${safe(n.category||'News')}</span><span class="status ${published?'published':rejected?'rejected':'pending'}">${published?'Published':rejected?'Rejected':'Under Review'}</span></div><h3>${safe(n.title)}</h3><p>${safe(n.content||'')}</p><div class="meta">Reporter: <b>${safe(n.reporterName||'Reporter')}</b> • ${safe(n.reporterEmail||'')}<br>Location: ${safe(n.location||'—')} • Submitted: ${fmt(n.createdAt)}</div><div class="actions">${actions}</div></div></article>`}).join('');list.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>review(b.dataset.action,b.dataset.id))}
async function review(action,id){const ref=db.collection('news').doc(id);try{if(action==='approve'){await ref.update({published:true,rejected:false,status:'Published',reviewedAt:firebase.firestore.FieldValue.serverTimestamp(),reviewedBy:auth.currentUser.email});msg('News approved and published.',true)}else if(action==='reject'){const reason=prompt('Reason for rejection (optional):','');await ref.update({published:false,rejected:true,status:'Rejected',rejectionReason:reason||'',reviewedAt:firebase.firestore.FieldValue.serverTimestamp(),reviewedBy:auth.currentUser.email});msg('News rejected.',true)}else if(action==='delete'){if(!confirm('Delete this news permanently?'))return;await ref.delete();msg('News deleted.',true)}await loadAll()}catch(e){console.error(e);msg('Action failed: '+(e.message||'Permission denied.'))}}
const filter=$('#filter');if(filter)filter.addEventListener('change',()=>loadAll().catch(e=>msg('Filter failed: '+(e.message||'Firestore error'))));const refresh=$('#refresh');if(refresh)refresh.addEventListener('click',()=>loadAll().catch(e=>msg('Refresh failed: '+(e.message||'Firestore error'))));const logout=$('#logout');if(logout)logout.addEventListener('click',()=>auth.signOut());
boot();
