const firebaseConfig={apiKey:'AIzaSyD1OSuBIx13ZXlxfispoGNjm-E0yZiuIio',authDomain:'chat-fe97c.firebaseapp.com',databaseURL:'https://chat-fe97c-default-rtdb.firebaseio.com',projectId:'chat-fe97c',storageBucket:'chat-fe97c.firebasestorage.app',messagingSenderId:'577320453917',appId:'1:577320453917:web:9a9d34cc088d0053ad03f4',measurementId:'G-H09PJFVCTT'};
let auth,db;
const $=s=>document.querySelector(s);
const ADMIN_CONFIGURED=typeof ADMIN_EMAIL==='string'&&!ADMIN_EMAIL.startsWith('CHANGE_THIS');
const safe=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const dateValue=v=>v?.toDate?v.toDate():v?.seconds?new Date(v.seconds*1000):null;
const fmt=v=>{const d=dateValue(v);return d?d.toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—'};
const img=n=>n?.imageData||n?.imageUrl||'';
function msg(t,good=false){const e=$('#message');e.textContent=t;e.className='message '+(good?'good':'bad')}
function loadScript(src){return new Promise((ok,no)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
async function boot(){try{await loadScript('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js');await loadScript('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth-compat.js');await loadScript('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore-compat.js');firebase.initializeApp(firebaseConfig);auth=firebase.auth();db=firebase.firestore();$('#loginForm').addEventListener('submit',login);auth.onAuthStateChanged(u=>{if(!u){$('#loginView').hidden=false;$('#dashboardView').hidden=true;return}if(!ADMIN_CONFIGURED||u.email?.toLowerCase()!==ADMIN_EMAIL.toLowerCase()){auth.signOut();msg('This Firebase account is not authorized as the site administrator.');return}$('#loginView').hidden=true;$('#dashboardView').hidden=false;$('#adminEmail').textContent=u.email;loadAll()})}catch(e){msg('Firebase could not be loaded. Refresh and try again.')}}
async function login(e){e.preventDefault();if(!ADMIN_CONFIGURED){msg('Admin email is not configured. Update admin-config.js first.');return}const email=$('#email').value.trim(),pass=$('#password').value;if(email.toLowerCase()!==ADMIN_EMAIL.toLowerCase()){msg('Wrong admin account. Use the configured admin email.');return}try{await auth.signInWithEmailAndPassword(email,pass)}catch(err){console.error(err);msg(err.code==='auth/invalid-credential'?'Invalid admin email or password.':err.message||'Admin login failed.')}}
async function loadAll(){const snap=await db.collection('news').get();const rows=[];snap.forEach(d=>rows.push({id:d.id,...d.data()}));rows.sort((a,b)=>(dateValue(b.createdAt)?.getTime()||0)-(dateValue(a.createdAt)?.getTime()||0));renderStats(rows);renderList(rows)}
function renderStats(rows){$('#total').textContent=rows.length;$('#pending').textContent=rows.filter(n=>n.status==='UnderReview'&&!n.rejected&&!n.published).length;$('#published').textContent=rows.filter(n=>n.published||n.status==='Published').length;$('#rejected').textContent=rows.filter(n=>n.rejected||n.status==='Rejected').length}
function renderList(rows){const filter=$('#filter').value;const show=rows.filter(n=>{if(filter==='pending')return n.status==='UnderReview'&&!n.rejected&&!n.published;if(filter==='published')return n.published||n.status==='Published';if(filter==='rejected')return n.rejected||n.status==='Rejected';return true});const list=$('#newsList');if(!show.length){list.innerHTML='<div class="empty">No stories in this section.</div>';return}list.innerHTML=show.map(n=>{const pending=n.status==='UnderReview'&&!n.rejected&&!n.published;const published=n.published||n.status==='Published';const rejected=n.rejected||n.status==='Rejected';let actions='';if(pending)actions=`<button class="approve" data-action="approve" data-id="${n.id}">✓ Approve</button><button class="reject" data-action="reject" data-id="${n.id}">✕ Reject</button>`;if(!pending)actions+=`<button class="delete" data-action="delete" data-id="${n.id}">Delete</button>`;return `<article class="news-item"><div class="thumb">${img(n)?`<img src="${safe(img(n))}" alt="">`:'NEWS'}</div><div class="story"><div class="top"><span class="tag">${safe(n.category||'News')}</span><span class="status ${published?'published':rejected?'rejected':'pending'}">${published?'Published':rejected?'Rejected':'Under Review'}</span></div><h3>${safe(n.title)}</h3><p>${safe(n.content||'')}</p><div class="meta">Reporter: <b>${safe(n.reporterName||'Reporter')}</b> • ${safe(n.reporterEmail||'')}<br>Location: ${safe(n.location||'—')} • Submitted: ${fmt(n.createdAt)}</div><div class="actions">${actions}</div></div></article>`}).join('');list.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>review(b.dataset.action,b.dataset.id))}
async function review(action,id){const ref=db.collection('news').doc(id);try{if(action==='approve'){await ref.update({published:true,rejected:false,status:'Published',reviewedAt:firebase.firestore.FieldValue.serverTimestamp(),reviewedBy:auth.currentUser.email});msg('News approved and published.',true)}else if(action==='reject'){const reason=prompt('Reason for rejection (optional):','');await ref.update({published:false,rejected:true,status:'Rejected',rejectionReason:reason||'',reviewedAt:firebase.firestore.FieldValue.serverTimestamp(),reviewedBy:auth.currentUser.email});msg('News rejected.',true)}else if(action==='delete'){if(!confirm('Delete this news permanently?'))return;await ref.delete();msg('News deleted.',true)}await loadAll()}catch(e){console.error(e);msg('Action failed: '+(e.message||'Permission denied.'))}}
$('#filter').addEventListener('change',loadAll);$('#refresh').addEventListener('click',loadAll);$('#logout').addEventListener('click',()=>auth.signOut());
boot();
