const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const toast=(m)=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
$('#today').textContent=new Intl.DateTimeFormat('te-IN',{dateStyle:'full'}).format(new Date());$('#year').textContent=new Date().getFullYear();
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('mm-dark',document.body.classList.contains('dark'))};if(localStorage.getItem('mm-dark')==='true')document.body.classList.add('dark');
$('#menuBtn').onclick=()=>$('#navLinks').classList.toggle('open');
function openModal(id){$('#'+id).classList.add('open')}function closeModal(e){e.currentTarget.closest('.modal').classList.remove('open')}
$$('[data-close]').forEach(x=>x.onclick=closeModal);$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
$$('[data-open]').forEach(b=>b.onclick=()=>{const card=b.closest('.news-card,.story');const title=card?.querySelector('h2,h3')?.textContent||'మహబూబాబాద్ జిల్లా తాజా వార్త';$('#modalTitle').textContent=title;openModal('articleModal')});
$('#reporterBtn').onclick=()=>openModal('loginModal');$('#reporterBtn2').onclick=()=>openModal('loginModal');
$('#loginBtn').onclick=()=>{const email=$('#email').value.trim();const pass=$('#password').value.trim();if(!email||!pass){toast('Email మరియు Password ఇవ్వండి');return}localStorage.setItem('mm-reporter',email);toast('Demo login successful — Reporter Dashboard త్వరలో');setTimeout(()=>$('#loginModal').classList.remove('open'),700)};
$('#searchBtn').onclick=()=>{const q=prompt('ఏ వార్త వెతకాలి?');if(!q)return;let found=0;$$('.news-card,.story').forEach(c=>{const ok=c.innerText.toLowerCase().includes(q.toLowerCase());c.style.display=ok?'':'none';if(ok)found++});toast(found+' వార్తలు కనిపించాయి')};
$('#notifyBtn').onclick=async()=>{if(!('Notification'in window)){toast('మీ browser notifications support చేయదు');return}const p=await Notification.requestPermission();toast(p==='granted'?'Notifications enabled':'Notifications permission not granted')};
let currentTitle='మహబూబాబాద్ జిల్లా ప్రజలకు తాజా స్థానిక సమాచారం';
function drawShare(title){const c=$('#shareCanvas'),x=c.getContext('2d');x.fillStyle='#f8f5ec';x.fillRect(0,0,c.width,c.height);x.fillStyle='#161616';x.fillRect(0,0,c.width,105);x.fillStyle='#fff';x.font='800 30px Arial';x.fillText('MANA MAHABUBABAD',55,67);x.fillStyle='#b91c1c';x.fillRect(55,145,130,8);x.fillStyle='#161616';x.font='800 64px Georgia';wrap(x,title,55,245,970,78,4);x.fillStyle='#aaa';x.fillRect(55,600,970,330);x.fillStyle='#888';x.font='800 28px Arial';x.fillText('NEWS IMAGE',410,775);x.fillStyle='#222';x.font='400 31px Arial';wrap(x,'మహబూబాబాద్ జిల్లాలోని తాజా సమాచారం, ప్రజలకు సంబంధించిన ముఖ్యమైన అంశాలు మరియు స్థానిక పరిణామాలను మన మహబూబాబాద్ మీ ముందుకు తీసుకువస్తోంది.',55,1000,970,45,5);x.fillStyle='#777';x.font='24px Arial';x.fillText('ManaMahabubabad • Today',55,1265);x.fillText(location.href,55,1305)}
function wrap(x,text,px,py,max,lh,maxLines){const words=text.split(' ');let line='',n=0;for(let w of words){const test=line+w+' ';if(x.measureText(test).width>max&&line){x.fillText(line,px,py);py+=lh;line=w+' ';if(++n>=maxLines)break}else line=test}if(n<maxLines)x.fillText(line,px,py)}
$$('[data-share]').forEach(b=>b.onclick=()=>{currentTitle=$('#modalTitle')?.textContent||'మహబూబాబాద్ జిల్లా తాజా సమాచారం';drawShare(currentTitle);openModal('shareModal')});
$('#downloadShare').onclick=()=>{const a=document.createElement('a');a.download='ManaMahabubabad-News.png';a.href=$('#shareCanvas').toDataURL('image/png');a.click();toast('Newspaper image downloaded')};
$('#copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('News link copied')}catch{toast('Copy failed')}};
$('#nativeShare').onclick=async()=>{const c=$('#shareCanvas');c.toBlob(async blob=>{const file=new File([blob],'ManaMahabubabad-News.png',{type:'image/png'});if(navigator.share){try{await navigator.share({title:currentTitle,text:'ManaMahabubabad News',files:[file]})}catch(e){} }else{await navigator.clipboard.writeText(location.href);toast('Link copied — share it on WhatsApp')}},'image/png')};
// Firebase-ready configuration. Add your Firebase web config here when connecting Auth/Firestore/Storage.
window.ManaMahabubabad={firebaseConfig:{apiKey:'',authDomain:'',projectId:'',storageBucket:'',messagingSenderId:'',appId:''},features:{auth:true,firestore:true,storage:true,push:true}};
